version: '3.8'

networks:
  inet:
    driver: overlay
    ipam:
      config:
        - subnet: 172.65.0.0/24

services:
  mariadb:
    restart: on-failure
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: irantalent_db
    networks:
      - inet

  webapp:
    restart: unless-stopped
    image: irantalentphp:7.4-apache
    volumes:
      - ./position:/var/www/html
      - "./conf:/etc/apache2/sites-available"
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - inet

  elasticsearch:
    restart: on-failure
    image: elasticsearch:7.9.3
    environment:
      cluster.name: elasticsearch
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
    ports:
      - "9200:9200"
    networks:
      - inet
